version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: tonycava
      MONGO_INITDB_ROOT_PASSWORD: password